// <auto-generated />
namespace Listonz.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddProfilePicture : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddProfilePicture));
        
        string IMigrationMetadata.Id
        {
            get { return "201311071347165_Add Profile Picture"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
