// <auto-generated />
namespace Listonz.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SocialColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SocialColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201311121553567_Social Column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
