// <auto-generated />
namespace Listonz.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CompanyIDField3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CompanyIDField3));
        
        string IMigrationMetadata.Id
        {
            get { return "201311060817420_CompanyIDField3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
